return {
  locations__ = {
    [1] = {
      foundation_config = "foundations",
      go_name = "hub",
      id = 1,
    },
    [2] = {
      foundation_config = "foundations_stone_mine",
      go_name = "dungeon",
      id = "stone_mine",
    },
    [3] = {
      foundation_config = "foundations_iron_mines",
      go_name = "iron_mine",
      id = "iron_mine",
    },
  },
  mines = {
    [1] = {
      p_iron = 0.001,
      point_offset_y = 0,
      layout = {
        [1] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [2] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [3] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [4] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [5] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [6] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [7] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [8] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
      },
      width = 15,
      density = 1,
      name = "MINES_1",
      p_copper = 0,
      point_offset_x = -4,
      height = 15,
    },
    [2] = {
      p_iron = 0.001,
      point_offset_y = 0,
      layout = {
        [1] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [2] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [3] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [4] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [5] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [6] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [7] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [8] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
      },
      width = 15,
      density = 1,
      name = "MINES_2",
      p_copper = 0,
      point_offset_x = -4,
      height = 15,
    },
    [3] = {
      p_iron = 0.2,
      point_offset_y = -4,
      layout = {
        [1] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [2] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [3] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [4] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [5] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [6] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [7] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [8] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
      },
      width = 15,
      density = 1,
      name = "MINES_3",
      p_copper = 0,
      point_offset_x = 0,
      height = 15,
    },
    [4] = {
      p_iron = 0.8,
      point_offset_y = 0,
      layout = {
        [1] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [2] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [3] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [4] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [5] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [6] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [7] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [8] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
      },
      width = 15,
      density = 1,
      name = "MINES_4",
      p_copper = 0,
      point_offset_x = -4,
      height = 15,
    },
    [5] = {
      p_iron = 0.8,
      point_offset_y = 0,
      layout = {
        [1] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [2] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [3] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [4] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [5] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [6] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [7] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [8] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
      },
      width = 15,
      density = 1,
      name = "MINES_5",
      p_copper = 0,
      point_offset_x = -4,
      height = 15,
    },
    [6] = {
      p_iron = 0.99,
      point_offset_y = 0,
      layout = {
        [1] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [2] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [3] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [4] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [5] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [6] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [7] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
        [8] = {
          [1] = 1,
          [2] = 1,
          [3] = 1,
          [4] = 1,
          [5] = 1,
          [6] = 1,
          [7] = 1,
          [8] = 1,
          [9] = 1,
          [10] = 1,
        },
      },
      width = 15,
      density = 1,
      name = "MINES_6",
      p_copper = 0,
      point_offset_x = -4,
      height = 15,
    },
  },
  foundations_art_test = {
    [1] = {
      number = 1,
      unlocks = {
        [1] = "F2",
      },
      price = 20,
      unlocked = true,
      sprite = "",
      name = "",
      revealed_count = 1,
      create_collision = false,
      guard_radius = "",
      type = "sell_point",
      tag = "F1",
    },
    [2] = {
      number = 2,
      unlocks = {
        [1] = "F3",
      },
      price = 20,
      unlocked = "",
      sprite = "",
      name = "stone",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F2",
    },
    [3] = {
      number = 3,
      unlocks = {
        [1] = "F4",
      },
      price = 10,
      unlocked = "",
      sprite = "",
      name = "source_stone",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F3",
    },
    [4] = {
      number = 4,
      unlocks = {
        [1] = "F5",
      },
      price = 40,
      unlocked = "",
      sprite = "",
      name = "source_stone",
      revealed_count = 2,
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F4",
    },
    [5] = {
      number = 5,
      unlocks = {
        [1] = "F6",
      },
      price = 20,
      unlocked = "",
      sprite = "",
      name = "wood",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F5",
    },
    [6] = {
      number = 6,
      unlocks = {
        [1] = "F7",
        [2] = "F8",
        [3] = "F10",
      },
      price = 20,
      unlocked = "",
      sprite = "",
      name = "source_tree",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F6",
    },
    [7] = {
      number = 7,
      unlocks = {
        [1] = "F13",
      },
      price = 80,
      unlocked = "",
      sprite = "",
      name = "source_tree",
      revealed_count = 3,
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F7",
    },
    [8] = {
      number = 8,
      unlocks = {
        [1] = "F9",
      },
      price = 40,
      unlocked = "",
      sprite = "",
      name = "iron",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F8",
    },
    [9] = {
      number = 11,
      unlocks = {
        [1] = "F11",
        [2] = "F15",
      },
      price = 50,
      unlocked = "",
      sprite = "",
      name = "source_iron",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F9",
    },
    [10] = {
      number = 9,
      unlocks = {
      },
      price = 100,
      unlocked = "",
      sprite = "",
      name = "source_stone",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F10",
    },
    [11] = {
      number = 10,
      unlocks = {
        [1] = "F12",
      },
      price = 80,
      unlocked = "",
      sprite = "",
      name = "stone_shield",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F11",
    },
    [12] = {
      number = 12,
      unlocks = {
        [1] = "F14",
        [2] = "F16",
      },
      price = 120,
      unlocked = "",
      sprite = "",
      name = "recipe_stone_shield",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "workbench",
      tag = "F12",
    },
    [13] = {
      number = 13,
      unlocks = {
      },
      price = 200,
      unlocked = "",
      sprite = "",
      name = "source_tree",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F13",
    },
    [14] = {
      number = 14,
      unlocks = {
      },
      price = 100,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "sell_point",
      tag = "F14",
    },
    [15] = {
      number = 15,
      unlocks = {
        [1] = "F18",
      },
      price = 200,
      unlocked = "",
      sprite = "",
      name = "source_iron",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F15",
    },
    [16] = {
      number = 16,
      unlocks = {
        [1] = "F17",
      },
      price = 200,
      unlocked = "",
      sprite = "",
      name = "stone_sword",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F16",
    },
    [17] = {
      number = 17,
      unlocks = {
        [1] = "F19",
      },
      price = 250,
      unlocked = "",
      sprite = "",
      name = "recipe_stone_sword",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "workbench",
      tag = "F17",
    },
    [18] = {
      number = 18,
      unlocks = {
      },
      price = 500,
      unlocked = "",
      sprite = "",
      name = "source_iron",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F18",
    },
    [19] = {
      number = 19,
      unlocks = {
        [1] = "F20",
      },
      price = 400,
      unlocked = "",
      sprite = "",
      name = "iron_shield",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F19",
    },
    [20] = {
      number = 20,
      unlocks = {
      },
      price = 500,
      unlocked = "",
      sprite = "",
      name = "recipe_iron_shield",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "workbench",
      tag = "F20",
    },
  },
  recipes = {
    [1] = {
      sprite = "recipe_stone_shield",
      name = "recipe_stone_shield",
      right = "stone",
      left = "stone",
      result = "stone_shield",
    },
    [2] = {
      sprite = "recipe_iron_shield",
      name = "recipe_iron_shield",
      right = "iron",
      left = "stone",
      result = "iron_shield",
    },
    [3] = {
      sprite = "recipe_stone_sword",
      name = "recipe_stone_sword",
      right = "stone",
      left = "wood",
      result = "stone_sword",
    },
    [4] = {
      sprite = "recipe_iron_sword",
      name = "recipe_iron_sword",
      right = "iron",
      left = "wood",
      result = "iron_sword",
    },
  },
  foundations_iron_mines = {
    [1] = {
      number = 1,
      unlocks = {
        [1] = "F2",
      },
      price = 0,
      unlocked = true,
      sprite = "",
      name = "MINES_4",
      revealed_count = 1,
      create_collision = false,
      guard_radius = "",
      type = "mines",
      tag = "F1",
    },
    [2] = {
      number = 2,
      unlocks = {
        [1] = "F3",
        [2] = "F4",
      },
      price = 30,
      unlocked = "",
      sprite = "",
      name = "NPC_MINER_2",
      revealed_count = 2,
      create_collision = false,
      guard_radius = "",
      type = "miner",
      tag = "F2",
    },
    [3] = {
      number = 3,
      unlocks = {
        [1] = "F5",
        [2] = "F6",
        [3] = "F8",
      },
      price = 70,
      unlocked = "",
      sprite = "",
      name = "MINES_5",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "mines",
      tag = "F3",
    },
    [4] = {
      number = 4,
      unlocks = {
        [1] = "F8",
      },
      price = 200,
      unlocked = "",
      sprite = "",
      name = "recipe_iron_shield",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "workbench",
      tag = "F8",
    },
    [5] = {
      number = 5,
      unlocks = {
        [1] = "F6",
      },
      price = 100,
      unlocked = "",
      sprite = "",
      name = "NPC_MINER_2",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "miner",
      tag = "F4",
    },
    [6] = {
      number = 6,
      unlocks = {
        [1] = "F7",
      },
      price = 300,
      unlocked = "",
      sprite = "",
      name = "NPC_MINER_1",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "miner",
      tag = "F6",
    },
    [7] = {
      number = 7,
      unlocks = {
      },
      price = 500,
      unlocked = "",
      sprite = "",
      name = "NPC_MINER_2",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "miner",
      tag = "F7",
    },
  },
  sources = {
    [1] = {
      sprite1 = "stone",
      regen_ticks = 100,
      drop3 = "",
      drop6 = "",
      sprite3 = "",
      sprite5 = "",
      sprite6 = "",
      drop5 = "",
      drop4 = "",
      name = "source_stone",
      sprite4 = "",
      drop2 = "stone",
      states_n = 2,
      drop1 = "",
      sprite2 = "stone_2",
    },
    [2] = {
      sprite1 = "tree",
      regen_ticks = 100,
      drop3 = "",
      drop6 = "",
      sprite3 = "",
      sprite5 = "",
      sprite6 = "",
      drop5 = "",
      drop4 = "",
      name = "source_tree",
      sprite4 = "",
      drop2 = "wood",
      states_n = 2,
      drop1 = "",
      sprite2 = "tree_2",
    },
    [3] = {
      sprite1 = "metall",
      regen_ticks = 100,
      drop3 = "",
      drop6 = "",
      sprite3 = "",
      sprite5 = "",
      sprite6 = "",
      drop5 = "",
      drop4 = "",
      name = "source_iron",
      sprite4 = "",
      drop2 = "iron",
      states_n = 2,
      drop1 = "",
      sprite2 = "metall_2",
    },
  },
  foundations_tree_td = {
    [1] = {
      number = 1,
      unlocks = {
        [1] = "F2",
      },
      price = 5,
      unlocked = true,
      sprite = "",
      name = "",
      revealed_count = 1,
      create_collision = true,
      guard_radius = 25,
      type = "guard",
      tag = "F1",
    },
    [2] = {
      number = 2,
      unlocks = {
        [1] = "F3",
        [2] = "F4",
        [3] = "F13",
      },
      price = 5,
      unlocked = "",
      sprite = "",
      name = "source_stone",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F2",
    },
    [3] = {
      number = 3,
      unlocks = {
        [1] = "F5.F8",
        [2] = "F9",
      },
      price = 5,
      unlocked = "",
      sprite = "",
      name = "source_stone",
      revealed_count = 2,
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F3",
    },
    [4] = {
      number = 4,
      unlocks = {
        [1] = "F6",
        [2] = "F8",
        [3] = "F9",
      },
      price = 5,
      unlocked = "",
      sprite = "",
      name = "source_stone",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F5",
    },
    [5] = {
      number = 5,
      unlocks = {
        [1] = "F19",
        [2] = "F8",
        [3] = "F9",
      },
      price = 8,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = 4,
      create_collision = true,
      guard_radius = 25,
      type = "guard",
      tag = "F4",
    },
    [6] = {
      number = 6,
      unlocks = {
        [1] = "F20",
        [2] = "F8",
        [3] = "F9",
      },
      price = 8,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = 5,
      create_collision = true,
      guard_radius = 25,
      type = "guard",
      tag = "F13",
    },
    [7] = {
      number = 7,
      unlocks = {
        [1] = "F11",
      },
      price = 5,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "wall",
      tag = "F8",
    },
    [8] = {
      number = 8,
      unlocks = {
        [1] = "F10",
      },
      price = 5,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = 3,
      create_collision = true,
      guard_radius = "",
      type = "wall",
      tag = "F9",
    },
    [9] = {
      number = 9,
      unlocks = {
      },
      price = 5,
      unlocked = "",
      sprite = "",
      name = "source_stone",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F6",
    },
    [10] = {
      number = 10,
      unlocks = {
      },
      price = 5,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "wall",
      tag = "F10",
    },
    [11] = {
      number = 11,
      unlocks = {
      },
      price = 5,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "wall",
      tag = "F11",
    },
    [12] = {
      number = 12,
      unlocks = {
        [1] = "F7",
        [2] = "F16",
        [3] = "F25",
      },
      price = 10,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "wall",
      tag = "F19",
    },
    [13] = {
      number = 13,
      unlocks = {
        [1] = "F12",
        [2] = "F16",
        [3] = "F24",
      },
      price = 10,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "wall",
      tag = "F20",
    },
    [14] = {
      number = 14,
      unlocks = {
      },
      price = 15,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "wall",
      tag = "F25",
    },
    [15] = {
      number = 15,
      unlocks = {
      },
      price = 15,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "wall",
      tag = "F24",
    },
    [16] = {
      number = 16,
      unlocks = {
        [1] = "F21",
      },
      price = 10,
      unlocked = "",
      sprite = "",
      name = "source_stone",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F12",
    },
    [17] = {
      number = 17,
      unlocks = {
        [1] = "F22",
      },
      price = 10,
      unlocked = "",
      sprite = "",
      name = "source_stone",
      revealed_count = 5,
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F21",
    },
    [18] = {
      number = 18,
      unlocks = {
      },
      price = 10,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "wall",
      tag = "F7",
    },
    [19] = {
      number = 19,
      unlocks = {
        [1] = "F15",
        [2] = "F17",
      },
      price = 20,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = 25,
      type = "guard",
      tag = "F16",
    },
    [20] = {
      number = 20,
      unlocks = {
        [1] = "F23",
      },
      price = 20,
      unlocked = "",
      sprite = "",
      name = "source_stone",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F22",
    },
    [21] = {
      number = 21,
      unlocks = {
      },
      price = 20,
      unlocked = "",
      sprite = "",
      name = "source_stone",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F23",
    },
    [22] = {
      number = 22,
      unlocks = {
        [1] = "F14",
      },
      price = 20,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "wall",
      tag = "F15",
    },
    [23] = {
      number = 23,
      unlocks = {
        [1] = "F18",
      },
      price = 20,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "wall",
      tag = "F17",
    },
    [24] = {
      number = 24,
      unlocks = {
      },
      price = 20,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "wall",
      tag = "F14",
    },
    [25] = {
      number = 25,
      unlocks = {
      },
      price = 20,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "wall",
      tag = "F18",
    },
    [26] = {
      number = 26,
      unlocks = {
      },
      price = "",
      unlocked = "",
      sprite = "",
      name = " ",
      revealed_count = "",
      create_collision = "",
      guard_radius = "",
      type = "",
      tag = "",
    },
    [27] = {
      number = 27,
      unlocks = {
      },
      price = "",
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = "",
      guard_radius = "",
      type = "",
      tag = "",
    },
    [28] = {
      number = 28,
      unlocks = {
      },
      price = "",
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = "",
      guard_radius = "",
      type = "",
      tag = "",
    },
    [29] = {
      number = 29,
      unlocks = {
      },
      price = "",
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = "",
      guard_radius = "",
      type = "",
      tag = "",
    },
    [30] = {
      number = 30,
      unlocks = {
      },
      price = "",
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = "",
      guard_radius = "",
      type = "",
      tag = "",
    },
    [31] = {
      number = 31,
      unlocks = {
      },
      price = "",
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = "",
      guard_radius = "",
      type = "",
      tag = "",
    },
    [32] = {
      number = 32,
      unlocks = {
      },
      price = "",
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = "",
      guard_radius = "",
      type = "",
      tag = "",
    },
  },
  waves_td = {
    [1] = {
      tick57 = "",
      wave_price = 4,
      tick7 = "WEAK",
      tick47 = "",
      tick15 = "",
      tick43 = "",
      tick60 = "",
      tick11 = "",
      tick66 = "",
      tick39 = "",
      tick34 = "",
      sum_health = 4,
      tick19 = "",
      tick63 = "",
      tick69 = "",
      tick4 = "",
      tick51 = "",
      wave = 1,
      tick54 = "",
      tick1 = "WEAK",
      tick27 = "",
      tick23 = "",
      tick31 = "",
      length = 15,
    },
    [2] = {
      tick57 = "",
      wave_price = 6,
      tick7 = "WEAK",
      tick47 = "",
      tick15 = "WEAK",
      tick43 = "",
      tick60 = "",
      tick11 = "",
      tick66 = "",
      tick39 = "",
      tick34 = "",
      sum_health = 6,
      tick19 = "",
      tick63 = "",
      tick69 = "",
      tick4 = "",
      tick51 = "",
      wave = 2,
      tick54 = "",
      tick1 = "WEAK",
      tick27 = "",
      tick23 = "",
      tick31 = "",
      length = 31,
    },
    [3] = {
      tick57 = "",
      wave_price = 4,
      tick7 = "",
      tick47 = "",
      tick15 = "",
      tick43 = "",
      tick60 = "",
      tick11 = "",
      tick66 = "",
      tick39 = "",
      tick34 = "",
      sum_health = 8,
      tick19 = "",
      tick63 = "",
      tick69 = "",
      tick4 = "",
      tick51 = "",
      wave = 4,
      tick54 = "",
      tick1 = "MEDIUM",
      tick27 = "",
      tick23 = "MEDIUM",
      tick31 = "",
      length = 23,
    },
    [4] = {
      tick57 = "",
      wave_price = 10,
      tick7 = "WEAK",
      tick47 = "WEAK",
      tick15 = "WEAK",
      tick43 = "",
      tick60 = "",
      tick11 = "",
      tick66 = "",
      tick39 = "WEAK",
      tick34 = "",
      sum_health = 10,
      tick19 = "",
      tick63 = "",
      tick69 = "",
      tick4 = "",
      tick51 = "",
      wave = 3,
      tick54 = "",
      tick1 = "WEAK",
      tick27 = "",
      tick23 = "",
      tick31 = "",
      length = 47,
    },
    [5] = {
      tick57 = "",
      wave_price = 6,
      tick7 = "",
      tick47 = "",
      tick15 = "MEDIUM",
      tick43 = "",
      tick60 = "",
      tick11 = "",
      tick66 = "",
      tick39 = "",
      tick34 = "",
      sum_health = 8,
      tick19 = "",
      tick63 = "",
      tick69 = "",
      tick4 = "",
      tick51 = "",
      wave = 4,
      tick54 = "",
      tick1 = "WEAK",
      tick27 = "",
      tick23 = "",
      tick31 = "WEAK",
      length = 31,
    },
    [6] = {
      tick57 = "",
      wave_price = 12,
      tick7 = "WEAK",
      tick47 = "",
      tick15 = "MEDIUM",
      tick43 = "",
      tick60 = "",
      tick11 = "",
      tick66 = "",
      tick39 = "WEAK",
      tick34 = "",
      sum_health = 16,
      tick19 = "",
      tick63 = "",
      tick69 = "",
      tick4 = "",
      tick51 = "",
      wave = 5,
      tick54 = "",
      tick1 = "WEAK",
      tick27 = "",
      tick23 = "MEDIUM",
      tick31 = "WEAK",
      length = 39,
    },
    [7] = {
      tick57 = "",
      wave_price = 18,
      tick7 = "WEAK",
      tick47 = "",
      tick15 = "MEDIUM",
      tick43 = "WEAK",
      tick60 = "",
      tick11 = "",
      tick66 = "",
      tick39 = "WEAK",
      tick34 = "WEAK",
      sum_health = 22,
      tick19 = "",
      tick63 = "",
      tick69 = "",
      tick4 = "",
      tick51 = "WEAK",
      wave = 6,
      tick54 = "",
      tick1 = "WEAK",
      tick27 = "",
      tick23 = "MEDIUM",
      tick31 = "WEAK",
      length = 52,
    },
    [8] = {
      tick57 = "",
      wave_price = 15,
      tick7 = "FAST",
      tick47 = "",
      tick15 = "FAST",
      tick43 = "",
      tick60 = "",
      tick11 = "",
      tick66 = "",
      tick39 = "",
      tick34 = "",
      sum_health = 5,
      tick19 = "",
      tick63 = "",
      tick69 = "",
      tick4 = "",
      tick51 = "",
      wave = 7,
      tick54 = "",
      tick1 = "FAST",
      tick27 = "",
      tick23 = "FAST",
      tick31 = "FAST",
      length = 31,
    },
    [9] = {
      tick57 = "",
      wave_price = 15,
      tick7 = "WEAK",
      tick47 = "",
      tick15 = "",
      tick43 = "FAST",
      tick60 = "",
      tick11 = "",
      tick66 = "",
      tick39 = "",
      tick34 = "FAST",
      sum_health = 9,
      tick19 = "",
      tick63 = "",
      tick69 = "",
      tick4 = "",
      tick51 = "FAST",
      wave = 8,
      tick54 = "",
      tick1 = "WEAK",
      tick27 = "",
      tick23 = "WEAK",
      tick31 = "",
      length = 51,
    },
    [10] = {
      tick57 = "",
      wave_price = 17,
      tick7 = "FAST",
      tick47 = "",
      tick15 = "FAST",
      tick43 = "",
      tick60 = "",
      tick11 = "",
      tick66 = "",
      tick39 = "",
      tick34 = "",
      sum_health = 9,
      tick19 = "",
      tick63 = "",
      tick69 = "",
      tick4 = "",
      tick51 = "",
      wave = 9,
      tick54 = "",
      tick1 = "MEDIUM",
      tick27 = "FAST",
      tick23 = "FAST",
      tick31 = "FAST",
      length = 31,
    },
    [11] = {
      tick57 = "",
      wave_price = 18,
      tick7 = "FAST",
      tick47 = "FAST",
      tick15 = "MEDIUM",
      tick43 = "",
      tick60 = "",
      tick11 = "",
      tick66 = "",
      tick39 = "FAST",
      tick34 = "",
      sum_health = 16,
      tick19 = "",
      tick63 = "",
      tick69 = "",
      tick4 = "",
      tick51 = "",
      wave = 10,
      tick54 = "",
      tick1 = "FAST",
      tick27 = "",
      tick23 = "MEDIUM",
      tick31 = "MEDIUM",
      length = 47,
    },
    [12] = {
      tick57 = "STRONG",
      wave_price = 20,
      tick7 = "STRONG",
      tick47 = "",
      tick15 = "WEAK",
      tick43 = "",
      tick60 = "",
      tick11 = "",
      tick66 = "",
      tick39 = "",
      tick34 = "",
      sum_health = 28,
      tick19 = "",
      tick63 = "WEAK",
      tick69 = "WEAK",
      tick4 = "",
      tick51 = "WEAK",
      wave = 11,
      tick54 = "",
      tick1 = "WEAK",
      tick27 = "",
      tick23 = "WEAK",
      tick31 = "",
      length = 69,
    },
    [13] = {
      tick57 = "",
      wave_price = 20,
      tick7 = "MEDIUM",
      tick47 = "",
      tick15 = "MEDIUM",
      tick43 = "",
      tick60 = "",
      tick11 = "WEAK",
      tick66 = "",
      tick39 = "",
      tick34 = "FAST",
      sum_health = 16,
      tick19 = "",
      tick63 = "",
      tick69 = "",
      tick4 = "",
      tick51 = "",
      wave = 12,
      tick54 = "",
      tick1 = "WEAK",
      tick27 = "FAST",
      tick23 = "FAST",
      tick31 = "FAST",
      length = 34,
    },
    [14] = {
      tick57 = "",
      wave_price = 14,
      tick7 = "",
      tick47 = "",
      tick15 = "",
      tick43 = "",
      tick60 = "",
      tick11 = "STRONG",
      tick66 = "",
      tick39 = "",
      tick34 = "",
      sum_health = 18,
      tick19 = "MEDIUM",
      tick63 = "",
      tick69 = "",
      tick4 = "MEDIUM",
      tick51 = "",
      wave = 13,
      tick54 = "",
      tick1 = "FAST",
      tick27 = "",
      tick23 = "FAST",
      tick31 = "",
      length = 23,
    },
    [15] = {
      tick57 = "",
      wave_price = 28,
      tick7 = "WEAK",
      tick47 = "WEAK",
      tick15 = "WEAK",
      tick43 = "",
      tick60 = "",
      tick11 = "",
      tick66 = "WEAK",
      tick39 = "",
      tick34 = "WEAK",
      sum_health = 28,
      tick19 = "WEAK",
      tick63 = "WEAK",
      tick69 = "WEAK",
      tick4 = "WEAK",
      tick51 = "WEAK",
      wave = 14,
      tick54 = "WEAK",
      tick1 = "WEAK",
      tick27 = "WEAK",
      tick23 = "",
      tick31 = "WEAK",
      length = 69,
    },
    [16] = {
      tick57 = "WEAK",
      wave_price = 34,
      tick7 = "",
      tick47 = "",
      tick15 = "STRONG",
      tick43 = "",
      tick60 = "WEAK",
      tick11 = "WEAK",
      tick66 = "",
      tick39 = "STRONG",
      tick34 = "WEAK",
      sum_health = 50,
      tick19 = "WEAK",
      tick63 = "STRONG",
      tick69 = "",
      tick4 = "STRONG",
      tick51 = "",
      wave = 15,
      tick54 = "WEAK",
      tick1 = "WEAK",
      tick27 = "WEAK",
      tick23 = "",
      tick31 = "WEAK",
      length = 69,
    },
  },
  foundations = {
    [1] = {
      number = 1,
      unlocks = {
        [1] = "F2",
      },
      price = 20,
      unlocked = true,
      sprite = "",
      name = "",
      revealed_count = 1,
      create_collision = false,
      guard_radius = "",
      type = "sell_point",
      tag = "F1",
    },
    [2] = {
      number = 2,
      unlocks = {
        [1] = "F3",
      },
      price = 10,
      unlocked = "",
      sprite = "",
      name = "wood",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F2",
    },
    [3] = {
      number = 3,
      unlocks = {
        [1] = "F4",
      },
      price = 20,
      unlocked = "",
      sprite = "",
      name = "source_tree",
      revealed_count = 3,
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F3",
    },
    [4] = {
      number = 4,
      unlocks = {
        [1] = "F5",
        [2] = "F7",
        [3] = "F10",
      },
      price = 40,
      unlocked = "",
      sprite = "",
      name = "source_tree",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F4",
    },
    [5] = {
      number = 5,
      unlocks = {
        [1] = "F6",
      },
      price = 10,
      unlocked = "",
      sprite = "",
      name = "stone",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F5",
    },
    [6] = {
      number = 6,
      unlocks = {
        [1] = "F8",
      },
      price = 20,
      unlocked = "",
      sprite = "mine_entry",
      name = "stone_mine",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "portal",
      tag = "F6",
    },
    [7] = {
      number = 7,
      unlocks = {
        [1] = "F13",
        [2] = "F10",
      },
      price = 80,
      unlocked = "",
      sprite = "",
      name = "source_tree",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F7",
    },
    [8] = {
      number = 8,
      unlocks = {
        [1] = "F11",
      },
      price = 150,
      unlocked = "",
      sprite = "",
      name = "stone_shield",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F8",
    },
    [9] = {
      number = 11,
      unlocks = {
        [1] = "F9",
      },
      price = 200,
      unlocked = "",
      sprite = "",
      name = "recipe_stone_shield",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "workbench",
      tag = "F11",
    },
    [10] = {
      number = 9,
      unlocks = {
        [1] = "F12",
      },
      price = 60,
      unlocked = "",
      sprite = "",
      name = "iron",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F9",
    },
    [11] = {
      number = 10,
      unlocks = {
      },
      price = 160,
      unlocked = "",
      sprite = "",
      name = "source_tree",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F10",
    },
    [12] = {
      number = 12,
      unlocks = {
        [1] = "F14",
      },
      price = 150,
      unlocked = "",
      sprite = "mine_entry",
      name = "iron_mine",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "portal",
      tag = "F12",
    },
    [13] = {
      number = 13,
      unlocks = {
      },
      price = 300,
      unlocked = "",
      sprite = "",
      name = "source_tree",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F13",
    },
    [14] = {
      number = 14,
      unlocks = {
        [1] = "F15",
      },
      price = 200,
      unlocked = "",
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "sell_point",
      tag = "F14",
    },
    [15] = {
      number = 15,
      unlocks = {
        [1] = "F16",
      },
      price = 450,
      unlocked = "",
      sprite = "",
      name = "stone_sword",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F15",
    },
    [16] = {
      number = 16,
      unlocks = {
        [1] = "F17",
      },
      price = 500,
      unlocked = "",
      sprite = "",
      name = "recipe_stone_sword",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "workbench",
      tag = "F16",
    },
    [17] = {
      number = 17,
      unlocks = {
        [1] = "F18",
      },
      price = 1200,
      unlocked = "",
      sprite = "",
      name = "iron_shield",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F17",
    },
    [18] = {
      number = 18,
      unlocks = {
      },
      price = 1300,
      unlocked = "",
      sprite = "",
      name = "recipe_iron_shield",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "workbench",
      tag = "F18",
    },
  },
  locations = {
    [1] = {
      foundation_config = "foundations",
      go_name = "hub",
      id = 1,
    },
    [2] = {
      foundation_config = "foundations_stone_mine",
      go_name = "dungeon",
      id = "stone_mine",
    },
    [3] = {
      foundation_config = "foundations_iron_mines",
      go_name = "iron_mine",
      id = "iron_mine",
    },
    [4] = {
      foundation_config = "foundations_tree_td",
      go_name = "td_demo",
      id = "td_demo",
    },
  },
  miners = {
    [1] = {
      target_2_type = "BUTTON",
      name = "NPC_MINER_1",
      target_1_element_name = "stone",
    },
    [2] = {
      target_2_type = "BUTTON",
      name = "NPC_MINER_2",
      target_1_element_name = "iron",
    },
  },
  locations_art_test = {
    [1] = {
      foundation_config = "foundations_art_test",
      go_name = "hub",
      id = 1,
    },
  },
  foundations_stone_mine = {
    [1] = {
      number = 1,
      unlocks = {
        [1] = "F2",
      },
      price = 0,
      unlocked = true,
      sprite = "",
      name = "MINES_1",
      revealed_count = 1,
      create_collision = false,
      guard_radius = "",
      type = "mines",
      tag = "F1",
    },
    [2] = {
      number = 2,
      unlocks = {
        [1] = "F3",
        [2] = "F4",
      },
      price = 30,
      unlocked = "",
      sprite = "",
      name = "NPC_MINER_1",
      revealed_count = 20,
      create_collision = false,
      guard_radius = "",
      type = "miner",
      tag = "F2",
    },
    [3] = {
      number = 3,
      unlocks = {
        [1] = "F5",
        [2] = "F6",
        [3] = "F8",
      },
      price = 70,
      unlocked = "",
      sprite = "",
      name = "MINES_2",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "mines",
      tag = "F3",
    },
    [4] = {
      number = 4,
      unlocks = {
        [1] = "F8",
      },
      price = 200,
      unlocked = "",
      sprite = "",
      name = "recipe_stone_shield",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "workbench",
      tag = "F8",
    },
    [5] = {
      number = 5,
      unlocks = {
        [1] = "F6",
      },
      price = 100,
      unlocked = "",
      sprite = "",
      name = "NPC_MINER_1",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "miner",
      tag = "F4",
    },
    [6] = {
      number = 6,
      unlocks = {
        [1] = "F7",
      },
      price = 300,
      unlocked = "",
      sprite = "",
      name = "NPC_MINER_1",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "miner",
      tag = "F6",
    },
    [7] = {
      number = 7,
      unlocks = {
      },
      price = 500,
      unlocked = "",
      sprite = "",
      name = "NPC_MINER_1",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "miner",
      tag = "F7",
    },
  },
  foundations_td = {
    [1] = {
      number = 1,
      type = "guard",
      name = "",
      revealed_count = 1,
      price = 22,
      create_collision = true,
      guard_radius = 25,
      tag = "F1",
    },
    [2] = {
      number = 2,
      type = "source",
      name = "source_stone",
      revealed_count = "",
      price = 5,
      create_collision = false,
      guard_radius = "",
      tag = "F2",
    },
    [3] = {
      number = 3,
      type = "source",
      name = "source_stone",
      revealed_count = 2,
      price = 5,
      create_collision = false,
      guard_radius = "",
      tag = "F3",
    },
    [4] = {
      number = 4,
      type = "source",
      name = "source_stone",
      revealed_count = "",
      price = 5,
      create_collision = false,
      guard_radius = "",
      tag = "F5",
    },
    [5] = {
      number = 5,
      type = "guard",
      name = "",
      revealed_count = 4,
      price = 10,
      create_collision = true,
      guard_radius = 25,
      tag = "F4",
    },
    [6] = {
      number = 6,
      type = "guard",
      name = "",
      revealed_count = 5,
      price = 10,
      create_collision = true,
      guard_radius = 25,
      tag = "F13",
    },
    [7] = {
      number = 7,
      type = "wall",
      name = "",
      revealed_count = "",
      price = 5,
      create_collision = true,
      guard_radius = "",
      tag = "F8",
    },
    [8] = {
      number = 8,
      type = "wall",
      name = "",
      revealed_count = 3,
      price = 5,
      create_collision = true,
      guard_radius = "",
      tag = "F9",
    },
    [9] = {
      number = 9,
      type = "source",
      name = "source_stone",
      revealed_count = "",
      price = 5,
      create_collision = false,
      guard_radius = "",
      tag = "F6",
    },
    [10] = {
      number = 10,
      type = "wall",
      name = "",
      revealed_count = "",
      price = 5,
      create_collision = true,
      guard_radius = "",
      tag = "F10",
    },
    [11] = {
      number = 11,
      type = "wall",
      name = "",
      revealed_count = "",
      price = 5,
      create_collision = true,
      guard_radius = "",
      tag = "F11",
    },
    [12] = {
      number = 12,
      type = "wall",
      name = "",
      revealed_count = "",
      price = 10,
      create_collision = true,
      guard_radius = "",
      tag = "F19",
    },
    [13] = {
      number = 13,
      type = "wall",
      name = "",
      revealed_count = "",
      price = 10,
      create_collision = true,
      guard_radius = "",
      tag = "F20",
    },
    [14] = {
      number = 14,
      type = "source",
      name = "source_stone",
      revealed_count = "",
      price = 10,
      create_collision = false,
      guard_radius = "",
      tag = "F12",
    },
    [15] = {
      number = 15,
      type = "source",
      name = "source_stone",
      revealed_count = 5,
      price = 10,
      create_collision = false,
      guard_radius = "",
      tag = "F21",
    },
    [16] = {
      number = 16,
      type = "wall",
      name = "",
      revealed_count = "",
      price = 10,
      create_collision = true,
      guard_radius = "",
      tag = "F7",
    },
    [17] = {
      number = 17,
      type = "guard",
      name = "",
      revealed_count = "",
      price = 20,
      create_collision = true,
      guard_radius = 25,
      tag = "F16",
    },
    [18] = {
      number = 18,
      type = "source",
      name = "source_stone",
      revealed_count = "",
      price = 20,
      create_collision = false,
      guard_radius = "",
      tag = "F22",
    },
    [19] = {
      number = 19,
      type = "source",
      name = "source_stone",
      revealed_count = "",
      price = 20,
      create_collision = false,
      guard_radius = "",
      tag = "F23",
    },
    [20] = {
      number = 20,
      type = "wall",
      name = "",
      revealed_count = "",
      price = 20,
      create_collision = true,
      guard_radius = "",
      tag = "F15",
    },
    [21] = {
      number = 21,
      type = "wall",
      name = "",
      revealed_count = "",
      price = 20,
      create_collision = true,
      guard_radius = "",
      tag = "F17",
    },
    [22] = {
      number = 22,
      type = "wall",
      name = "",
      revealed_count = "",
      price = 20,
      create_collision = true,
      guard_radius = "",
      tag = "F14",
    },
    [23] = {
      number = 23,
      type = "wall",
      name = "",
      revealed_count = "",
      price = 20,
      create_collision = true,
      guard_radius = "",
      tag = "F18",
    },
  },
  elements = {
    [1] = {
      sprite = "element_object",
      buy_price = 0,
      name = "object",
      visible = true,
      sell_price = 0,
      static = false,
      components = "{}",
      light = "",
    },
    [2] = {
      sprite = "element_stone_shield",
      buy_price = 8,
      name = "stone_shield",
      visible = "",
      sell_price = 50,
      static = "",
      components = "{stone, stone}",
      light = "",
    },
    [3] = {
      sprite = "element_iron_shield",
      buy_price = 16,
      name = "iron_shield",
      visible = "",
      sell_price = 200,
      static = "",
      components = "{stone, iron}",
      light = "",
    },
    [4] = {
      sprite = "element_stone_sword",
      buy_price = 5,
      name = "stone_sword",
      visible = "",
      sell_price = 100,
      static = "",
      components = "{wood, stone}",
      light = "",
    },
    [5] = {
      sprite = "element_iron_sword",
      buy_price = 16,
      name = "iron_sword",
      visible = "",
      sell_price = 10,
      static = "",
      components = "{wood, iron}",
      light = "",
    },
    [6] = {
      sprite = "element_buff_yellow",
      buy_price = 12,
      name = "orb",
      visible = "",
      sell_price = 9,
      static = "",
      components = "{}",
      light = "white",
    },
    [7] = {
      sprite = "element_buff_yellow",
      buy_price = "",
      name = "bulb",
      visible = false,
      sell_price = "",
      static = true,
      components = "{}",
      light = "sun_",
    },
    [8] = {
      sprite = "element_wood",
      buy_price = 2,
      name = "wood",
      visible = "",
      sell_price = 5,
      static = "",
      components = "{}",
      light = "",
    },
    [9] = {
      sprite = "element_stone",
      buy_price = 2,
      name = "stone",
      visible = "",
      sell_price = 20,
      static = "",
      components = "{}",
      light = "",
    },
    [10] = {
      sprite = "element_iron",
      buy_price = 5,
      name = "iron",
      visible = "",
      sell_price = 40,
      static = "",
      components = "{}",
      light = "",
    },
  },
  Copy_of_foundations = {
    [1] = {
      number = 1,
      unlocks = {
        [1] = "F24",
      },
      price = 20,
      unlocked = true,
      sprite = "",
      name = "",
      revealed_count = 1,
      create_collision = true,
      guard_radius = "",
      type = "sell_point",
      tag = "F1",
    },
    [2] = {
      number = 2,
      unlocks = {
        [1] = "F18",
      },
      price = 20,
      unlocked = true,
      sprite = "mine_entry",
      name = "stone_mine",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "portal",
      tag = "F24",
    },
    [3] = {
      number = 3,
      unlocks = {
        [1] = "F2",
      },
      price = 500,
      unlocked = true,
      sprite = "mine_entry",
      name = "iron_mine",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "portal",
      tag = "F18",
    },
    [4] = {
      number = 4,
      unlocks = {
        [1] = "F3",
      },
      price = 20,
      unlocked = true,
      sprite = "",
      name = "stone",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F2",
    },
    [5] = {
      number = 5,
      unlocks = {
        [1] = "F4",
      },
      price = 10,
      unlocked = true,
      sprite = "",
      name = "source_stone",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F3",
    },
    [6] = {
      number = 6,
      unlocks = {
        [1] = "F5",
      },
      price = 40,
      unlocked = true,
      sprite = "",
      name = "source_stone",
      revealed_count = 2,
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F4",
    },
    [7] = {
      number = 7,
      unlocks = {
        [1] = "F6",
      },
      price = 20,
      unlocked = true,
      sprite = "",
      name = "wood",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F5",
    },
    [8] = {
      number = 8,
      unlocks = {
        [1] = "F7",
      },
      price = 20,
      unlocked = true,
      sprite = "",
      name = "source_tree",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F6",
    },
    [9] = {
      number = 9,
      unlocks = {
        [1] = "F8",
      },
      price = 80,
      unlocked = true,
      sprite = "",
      name = "source_tree",
      revealed_count = 3,
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F7",
    },
    [10] = {
      number = 10,
      unlocks = {
        [1] = "F9",
      },
      price = 60,
      unlocked = true,
      sprite = "",
      name = "iron",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F8",
    },
    [11] = {
      number = 11,
      unlocks = {
        [1] = "F10",
      },
      price = 70,
      unlocked = true,
      sprite = "",
      name = "source_iron",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F9",
    },
    [12] = {
      number = 12,
      unlocks = {
        [1] = "F11",
      },
      price = 100,
      unlocked = true,
      sprite = "",
      name = "source_stone",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F10",
    },
    [13] = {
      number = 13,
      unlocks = {
        [1] = "F12",
      },
      price = 150,
      unlocked = true,
      sprite = "",
      name = "stone_shield",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F11",
    },
    [14] = {
      number = 14,
      unlocks = {
        [1] = "F13",
      },
      price = 200,
      unlocked = true,
      sprite = "",
      name = "recipe_stone_shield",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "workbench",
      tag = "F12",
    },
    [15] = {
      number = 15,
      unlocks = {
        [1] = "F14",
      },
      price = 200,
      unlocked = true,
      sprite = "",
      name = "source_tree",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F13",
    },
    [16] = {
      number = 16,
      unlocks = {
        [1] = "F15",
      },
      price = 200,
      unlocked = true,
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "sell_point",
      tag = "F14",
    },
    [17] = {
      number = 17,
      unlocks = {
        [1] = "F16",
      },
      price = 200,
      unlocked = true,
      sprite = "",
      name = "source_iron",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F15",
    },
    [18] = {
      number = 18,
      unlocks = {
        [1] = "F17",
      },
      price = 450,
      unlocked = true,
      sprite = "",
      name = "stone_sword",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F16",
    },
    [19] = {
      number = 19,
      unlocks = {
        [1] = "F19",
      },
      price = 500,
      unlocked = true,
      sprite = "",
      name = "recipe_stone_sword",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "workbench",
      tag = "F17",
    },
    [20] = {
      number = 20,
      unlocks = {
        [1] = "F20",
      },
      price = 1200,
      unlocked = true,
      sprite = "",
      name = "iron_shield",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "reserved_stand",
      tag = "F19",
    },
    [21] = {
      number = 21,
      unlocks = {
        [1] = "F23",
      },
      price = 1300,
      unlocked = true,
      sprite = "",
      name = "recipe_iron_shield",
      revealed_count = "",
      create_collision = true,
      guard_radius = "",
      type = "workbench",
      tag = "F20",
    },
    [22] = {
      number = 22,
      unlocks = {
        [1] = "F21",
      },
      price = 1000,
      unlocked = true,
      sprite = "",
      name = "source_iron",
      revealed_count = "",
      create_collision = false,
      guard_radius = "",
      type = "source",
      tag = "F23",
    },
    [23] = {
      number = 23,
      unlocks = {
        [1] = "F22",
      },
      price = 70,
      unlocked = true,
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = true,
      guard_radius = 25,
      type = "guard",
      tag = "F21",
    },
    [24] = {
      number = 24,
      unlocks = {
      },
      price = 150,
      unlocked = true,
      sprite = "",
      name = "",
      revealed_count = "",
      create_collision = false,
      guard_radius = 25,
      type = "guard",
      tag = "F22",
    },
  },
  enemies_td = {
    [1] = {
      health = 2,
      skin = 10,
      speed = 0.25,
      name = "WEAK",
      reward = 2,
    },
    [2] = {
      health = 1,
      skin = 9,
      speed = 0.7,
      name = "FAST",
      reward = 3,
    },
    [3] = {
      health = 4,
      skin = 8,
      speed = 0.4,
      name = "MEDIUM",
      reward = 2,
    },
    [4] = {
      health = 8,
      skin = 7,
      speed = 0.3,
      name = "STRONG",
      reward = 4,
    },
    [5] = {
      health = 12,
      skin = 2,
      speed = 0.3,
      name = "GIGA",
      reward = 8,
    },
  },
}
